import type { BomDisplayNode, BomDirection } from "./types";

// 정전개 (V6 엔진 ASS'Y 기준)
const forwardTree: BomDisplayNode = {
  nodeKey: "root",
  partId: "engine-v6-001",
  part_number: "ENG-V6-001",
  name: "V6 엔진 ASS'Y",
  quantity: 1,
  material: null,
  revision: "B",
  lifecycle_state: "양산",
  unit: "EA",
  category: "ASS'Y",
  children: [
    {
      nodeKey: "root.0",
      partId: "engine-v6-001-01",
      part_number: "ENG-V6-001-01",
      name: "실린더 블록",
      quantity: 1,
      material: "주철 (FC250)",
      revision: "A",
      lifecycle_state: "양산",
      unit: "EA",
      category: "가공품",
      children: [
        {
          nodeKey: "root.0.0",
          partId: "engine-v6-001-01-01",
          part_number: "ENG-V6-001-01-01",
          name: "실린더 라이너",
          quantity: 6,
          material: "주철 (FC300)",
          revision: "A",
          lifecycle_state: "양산",
          unit: "EA",
          category: "가공품",
          children: [],
        },
        {
          nodeKey: "root.0.1",
          partId: "engine-v6-001-01-02",
          part_number: "ENG-V6-001-01-02",
          name: "헤드 가스켓",
          quantity: 1,
          material: "MLS (Multi-Layer Steel)",
          revision: "C",
          lifecycle_state: "양산",
          unit: "EA",
          category: "구매품",
          children: [],
        },
      ],
    },
    {
      nodeKey: "root.1",
      partId: "engine-v6-001-02",
      part_number: "ENG-V6-001-02",
      name: "피스톤 ASS'Y",
      quantity: 6,
      material: null,
      revision: "B",
      lifecycle_state: "양산",
      unit: "EA",
      category: "ASS'Y",
      children: [
        {
          nodeKey: "root.1.0",
          partId: "engine-v6-001-02-01",
          part_number: "ENG-V6-001-02-01",
          name: "피스톤",
          quantity: 1,
          material: "알루미늄 합금 (A4032)",
          revision: "A",
          lifecycle_state: "양산",
          unit: "EA",
          category: "가공품",
          children: [],
        },
        {
          nodeKey: "root.1.1",
          partId: "engine-v6-001-02-02",
          part_number: "ENG-V6-001-02-02",
          name: "피스톤 링",
          quantity: 3,
          material: "주철 (FC250)",
          revision: "A",
          lifecycle_state: "양산",
          unit: "EA",
          category: "구매품",
          children: [],
        },
        {
          nodeKey: "root.1.2",
          partId: "engine-v6-001-02-03",
          part_number: "ENG-V6-001-02-03",
          name: "피스톤 핀",
          quantity: 1,
          material: "크롬몰리브덴강 (SCM415)",
          revision: "A",
          lifecycle_state: "양산",
          unit: "EA",
          category: "가공품",
          children: [],
        },
      ],
    },
    {
      nodeKey: "root.2",
      partId: "engine-v6-001-03",
      part_number: "ENG-V6-001-03",
      name: "크랭크샤프트",
      quantity: 1,
      material: "탄소강 (S45C)",
      revision: "A",
      lifecycle_state: "양산",
      unit: "EA",
      category: "가공품",
      children: [],
    },
    {
      nodeKey: "root.3",
      partId: "engine-v6-001-04",
      part_number: "ENG-V6-001-04",
      name: "커넥팅 로드",
      quantity: 6,
      material: "단조강 (SCM440)",
      revision: "B",
      lifecycle_state: "양산",
      unit: "EA",
      category: "가공품",
      children: [],
    },
    {
      nodeKey: "root.4",
      partId: "engine-v6-001-05",
      part_number: "ENG-V6-001-05",
      name: "오일 펌프 ASS'Y",
      quantity: 1,
      material: null,
      revision: "A",
      lifecycle_state: "개발",
      unit: "EA",
      category: "ASS'Y",
      children: [
        {
          nodeKey: "root.4.0",
          partId: "engine-v6-001-05-01",
          part_number: "ENG-V6-001-05-01",
          name: "로터",
          quantity: 1,
          material: "소결합금",
          revision: "A",
          lifecycle_state: "개발",
          unit: "EA",
          category: "가공품",
          children: [],
        },
        {
          nodeKey: "root.4.1",
          partId: "engine-v6-001-05-02",
          part_number: "ENG-V6-001-05-02",
          name: "하우징",
          quantity: 1,
          material: "알루미늄 (ADC12)",
          revision: "A",
          lifecycle_state: "개발",
          unit: "EA",
          category: "가공품",
          children: [],
        },
      ],
    },
  ],
};

// 역전개 (피스톤 기준 — 상위 어셈블리 트리)
const reverseTree: BomDisplayNode = {
  nodeKey: "root",
  partId: "engine-v6-001-02-01",
  part_number: "ENG-V6-001-02-01",
  name: "피스톤",
  quantity: 1,
  material: "알루미늄 합금 (A4032)",
  revision: "A",
  lifecycle_state: "양산",
  unit: "EA",
  category: "가공품",
  children: [
    {
      nodeKey: "root.0",
      partId: "engine-v6-001-02",
      part_number: "ENG-V6-001-02",
      name: "피스톤 ASS'Y",
      quantity: 6,
      material: null,
      revision: "B",
      lifecycle_state: "양산",
      unit: "EA",
      category: "ASS'Y",
      children: [
        {
          nodeKey: "root.0.0",
          partId: "engine-v6-001",
          part_number: "ENG-V6-001",
          name: "V6 엔진 ASS'Y",
          quantity: 1,
          material: null,
          revision: "B",
          lifecycle_state: "양산",
          unit: "EA",
          category: "ASS'Y",
          children: [
            {
              nodeKey: "root.0.0.0",
              partId: "vehicle-sedan-001",
              part_number: "VHC-SDN-001",
              name: "세단 차량",
              quantity: 1,
              material: null,
              revision: "A",
              lifecycle_state: "양산",
              unit: "EA",
              category: "완성품",
              children: [],
            },
          ],
        },
      ],
    },
  ],
};

export function getMockBomTree(
  _partId: string,
  direction: BomDirection,
): BomDisplayNode {
  return direction === "forward" ? forwardTree : reverseTree;
}
