export const TEMPLATE_MAPPING_PROPERTY_LABELS: Record<string, string> = {
  part_number: "품번",
  name: "부품명",
  revision: "리비전",
  material: "재질",
  unit: "단위",
  unit_price: "단가",
  specification: "규격",
  description: "설명",
  category: "분류",
  is_phantom: "팬텀 여부",
  lifecycle_state: "수명주기",
  lead_time_days: "리드타임(일)",
  company_name: "업체명",
  code: "업체코드",
  contact: "담당자",
  country: "국가",
  contact_info: "연락처",
  lead_time: "납기(일)",
  drawing_number: "도면번호",
  file_path: "파일경로",
  version: "버전",
  status: "상태",
  project_code: "프로젝트코드",
  manager: "담당자",
  target_date: "목표일",
  quantity: "수량",
  sequence: "순서",
  reference_designator: "참조번호",
  find_number: "찾기번호",
  unit_cost: "단가",
};
