import type { DeepDefined } from "@/api/types";
import type { components } from "@/api/generated/schema";

export type AddTeamMembersRequestDto = components["schemas"]["AddTeamMembersRequest"];
export type ChangeMemberRoleRequestDto = components["schemas"]["ChangeRoleRequest"];
export type CreateInvitationRequestDto = components["schemas"]["CreateInvitationRequest"];
export type CreateTeamRequestDto = components["schemas"]["CreateTeamRequest"];
export type InvitationListResponseDto = DeepDefined<components["schemas"]["InvitationListResponse"]>;
export type InvitationResponseDto = DeepDefined<components["schemas"]["InvitationResponse"]>;
export type LabelListResponseDto = DeepDefined<components["schemas"]["LabelListResponse"]>;
export type LabelResponseDto = DeepDefined<components["schemas"]["LabelResponse"]>;
export type MemberListResponseDto = DeepDefined<components["schemas"]["MemberListResponse"]>;
export type MemberSummaryDto = DeepDefined<components["schemas"]["MemberSummaryResponse"]>;
export type ProfileImageResponseDto = DeepDefined<components["schemas"]["ProfileImageResponse"]>;
export type RemoveTeamMembersRequestDto = components["schemas"]["RemoveTeamMembersRequest"];
export type SetProfileImageRequestDto = components["schemas"]["SetProfileImageRequest"];
export type TeamListResponseDto = DeepDefined<components["schemas"]["TeamListResponse"]>;
export type TeamMemberListResponseDto = DeepDefined<components["schemas"]["TeamMemberListResponse"]>;
export type TeamMemberSummaryDto = DeepDefined<components["schemas"]["TeamMemberItemResponse"]>;
export type TeamSummaryDto = DeepDefined<components["schemas"]["TeamSummaryItemResponse"]>;
export type UserSummaryDto = DeepDefined<components["schemas"]["UserSummaryResponse"]>;
export type CreateLabelRequestDto = components["schemas"]["CreateLabelRequest"];
