import type { ItemData, TreeNodeData } from "./types";

// 통합 트리 구조: 프로젝트 > 폴더 > 아이템
export const mockFolders: TreeNodeData[] = [
  {
    id: "f1",
    name: "엔진 프로젝트",
    type: "project",
    description: "V6/V8 엔진 개발 프로젝트",
    lastUpdated: "2024-01-15",
    children: [
      {
        id: "f1-1",
        name: "V6 엔진",
        type: "folder",
        itemCount: 12,
        children: [
          {
            id: "item-1",
            name: "V6 엔진 ASS'Y",
            type: "item",
            partNumber: "ENG-V6-001",
            status: "conflict",
            hasDrawing: true,
            children: [
              {
                id: "item-1-1",
                name: "실린더 블록",
                type: "item",
                partNumber: "ENG-V6-001-01",
                status: "approved",
                hasDrawing: true,
              },
              {
                id: "item-1-2",
                name: "피스톤 ASS'Y",
                type: "item",
                partNumber: "ENG-V6-001-02",
                status: "approved",
                hasDrawing: true,
              },
              {
                id: "item-1-3",
                name: "크랭크샤프트",
                type: "item",
                partNumber: "ENG-V6-001-03",
                status: "draft",
                hasDrawing: true,
              },
              {
                id: "item-1-4",
                name: "커넥팅 로드",
                type: "item",
                partNumber: "ENG-V6-001-04",
                status: "none",
                hasDrawing: false,
              },
            ],
          },
        ],
      },
      {
        id: "f1-2",
        name: "V8 엔진",
        type: "folder",
        itemCount: 8,
      },
    ],
  },
  {
    id: "f2",
    name: "변속기 프로젝트",
    type: "project",
    description: "자동 변속기 개발 프로젝트",
    lastUpdated: "2024-01-14",
    children: [
      {
        id: "f2-1",
        name: "6단 자동",
        type: "folder",
        itemCount: 6,
        children: [
          {
            id: "item-2",
            name: "6단 자동변속기 ASS'Y",
            type: "item",
            partNumber: "TRN-6AT-001",
            status: "draft",
            hasDrawing: true,
            children: [
              {
                id: "item-2-1",
                name: "토크 컨버터",
                type: "item",
                partNumber: "TRN-6AT-001-01",
                status: "approved",
                hasDrawing: true,
              },
              {
                id: "item-2-2",
                name: "유성 기어 세트",
                type: "item",
                partNumber: "TRN-6AT-001-02",
                status: "draft",
                hasDrawing: false,
              },
            ],
          },
        ],
      },
      {
        id: "f2-2",
        name: "8단 자동",
        type: "folder",
        itemCount: 4,
      },
    ],
  },
  {
    id: "f3",
    name: "섀시 프로젝트",
    type: "project",
    description: "차체 및 섀시 부품 프로젝트",
    lastUpdated: "2024-01-13",
  },
];

export const mockItems: Record<string, ItemData[]> = {
  "f1-1": [
    {
      id: "item-1",
      partNumber: "ENG-V6-001",
      name: "V6 엔진 ASS'Y",
      material: "SUS304",
      quantity: 1,
      unit: "EA",
      drawingStatus: "approved",
      drawingThumbnail: "/drawing-placeholder.svg",
      aiAnalyzed: true,
      conflicts: [
        {
          id: "c1",
          type: "material",
          field: "재질",
          drawingValue: "SUS304",
          excelValue: "SUS316",
          severity: "error",
        },
      ],
      children: [
        {
          id: "item-1-1",
          partNumber: "ENG-V6-001-01",
          name: "실린더 블록",
          material: "FC250",
          quantity: 1,
          unit: "EA",
          drawingStatus: "approved",
          children: [
            {
              id: "item-1-1-1",
              partNumber: "ENG-V6-001-01-01",
              name: "실린더 라이너",
              material: "FC300",
              quantity: 6,
              unit: "EA",
              drawingStatus: "approved",
            },
            {
              id: "item-1-1-2",
              partNumber: "ENG-V6-001-01-02",
              name: "워터 재킷 가스켓",
              material: "NBR",
              quantity: 2,
              unit: "EA",
              drawingStatus: "draft",
            },
          ],
        },
        {
          id: "item-1-2",
          partNumber: "ENG-V6-001-02",
          name: "피스톤 ASS'Y",
          material: "AL6061",
          quantity: 6,
          unit: "SET",
          drawingStatus: "approved",
          children: [
            {
              id: "item-1-2-1",
              partNumber: "ENG-V6-001-02-01",
              name: "피스톤",
              material: "AL6061-T6",
              quantity: 1,
              unit: "EA",
              drawingStatus: "approved",
            },
            {
              id: "item-1-2-2",
              partNumber: "ENG-V6-001-02-02",
              name: "피스톤 링 세트",
              material: "STKM13A",
              quantity: 1,
              unit: "SET",
              drawingStatus: "approved",
            },
            {
              id: "item-1-2-3",
              partNumber: "ENG-V6-001-02-03",
              name: "피스톤 핀",
              material: "SCM420",
              quantity: 1,
              unit: "EA",
              drawingStatus: "draft",
            },
          ],
        },
        {
          id: "item-1-3",
          partNumber: "ENG-V6-001-03",
          name: "크랭크샤프트",
          material: "S45C",
          quantity: 1,
          unit: "EA",
          drawingStatus: "approved",
        },
        {
          id: "item-1-4",
          partNumber: "ENG-V6-001-04",
          name: "커넥팅 로드",
          material: "SCM440",
          quantity: 6,
          unit: "EA",
          drawingStatus: "none",
        },
      ],
    },
  ],
  "f2-1": [
    {
      id: "item-2",
      partNumber: "TRN-6AT-001",
      name: "6단 자동변속기 ASS'Y",
      material: "AL-DIE",
      quantity: 1,
      unit: "EA",
      drawingStatus: "draft",
      children: [
        {
          id: "item-2-1",
          partNumber: "TRN-6AT-001-01",
          name: "토크 컨버터",
          material: "SPCC",
          quantity: 1,
          unit: "EA",
          drawingStatus: "approved",
        },
        {
          id: "item-2-2",
          partNumber: "TRN-6AT-001-02",
          name: "유성 기어 세트",
          material: "SCM420H",
          quantity: 2,
          unit: "SET",
          drawingStatus: "draft",
        },
      ],
    },
  ],
};

export const defaultFolderId = "f1-1";
